### ISSUE TITLE
Can't choose empty workspace by thumbnail

### ISSUE THREAD

**Issue by vantu5z** [AlynxZhou/gnome-shell-extension-always-show-workspace-thumbnails#1]
If I click on empty thumbnail, it does not switch to empty workspace and will open current.

**Comment by AlynxZhou** [comment]
I cannot reproduce it, please attach a video, or maybe you find an upstream bug, please send a issue to GNOME GitLab, because this extension only return true when asking to display thumbnail, your problem should have no relationship to it.

**Comment by vantu5z** [comment]
Sorry it was Dash-to-Panel extension.
