### ISSUE TITLE
Extension is not updated on extensions.gnome.org

### ISSUE THREAD

**Issue by Arteusz** [AlynxZhou/gnome-shell-extension-always-show-workspace-thumbnails#5]
Extension shows only version 40 and 41 on https://extensions.gnome.org/extension/4156/always-show-workspace-thumbnails/

![image](https://user-images.githubusercontent.com/2125455/164449833-ed010b2c-8199-4b62-a5aa-71797962fb5d.png)

This results in extension being disabled and marked as outdated, with no way to update it from gnome Extensions app.
I saw that #3 was closed and after I manually update the extension it works. 

Please update manifest file on extensions.gnome.org so the extension can be updated semi-automatically.

**Comment by AlynxZhou** [comment]
Thanks for the reminder! I just uploaded latest release to e.g.o.
