### ISSUE TITLE
Add support for GNOME 44

### ISSUE THREAD

**Issue by erenfro** [AlynxZhou/gnome-shell-extension-always-show-workspace-thumbnails#7]
Add support for GNOME 44.

**Comment by AlynxZhou** [comment]
Try to add `"44"` here by yourself first, I don't have GNOME 44 currently: <https://github.com/AlynxZhou/gnome-shell-extension-always-show-workspace-thumbnails/blob/master/metadata.json#L7>.

**Comment by erenfro** [comment]
I have tested this and it seems to work just fine on Gnome 44.0 and 44.1.

**Comment by rastersoft** [comment]
Tested in Ubuntu with Gnome 44.2. It works fine. Can you update it in extensions.gnome.org, please?

**Comment by AlynxZhou** [comment]
> Tested in Ubuntu with Gnome 44.2. It works fine. Can you update it in extensions.gnome.org, please?

Done
